version: '3.8'

services:
  db:
    image: postgres:15
    container_name: therapist-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: therapist_directory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: therapist-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:${POSTGRES_PASSWORD}@db:5432/therapist_directory
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/code
      - ./backend/uploads:/code/uploads

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5050:80"

  frontend:
    build: ./frontend
    container_name: therapist-frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgres_data:

